Handle usernames/passwords with strange characters
Without the quotes I was getting:

/jenkins/workspace/****@tmp/durable-abcdef12/script.sh: line 2: syntax
error: EOF in backquote substitution

Because I had a ` in my generated password